### PR TITLE
fixup! ocaml: add 4.14

### PR DESCRIPTION
**Pull request by edwintorok**
MD5SUM of gen_ocaml_config.ml.in didn't match due to some differences in final newlines.

### CODE REVIEW

**Comment by edwintorok** [comment]
There are still some failures though, although 0.22.4 is present, perhaps there is a reason it can't pick it:
The following dependencies couldn't be met:
  - ocamlformat -> ocaml < 4.14
      base of this switch (use `--unlock-base' to force)

**Comment by edwintorok** [comment]
ah the problem there will be that it'll try to install all packages, both 4.13 and 4.14. which won't work.

**Comment by psafont** [comment]
That's unfortunate, at some point I remember there were different versions depending on the version that needed to be installed, so it should have been handled

**Comment by edwintorok** [comment]
I have a 4.14-build branch where I delete the 2 conflicting packages from 4.13 and that works

**Comment by edwintorok** [comment]
remove duplicates from 4.14 branch

 packages/upstream/ocamlformat.0.19.0/opam | 59 -----------------------------------------------------------
 packages/upstream/odoc-parser.0.9.0/opam  | 36 ------------------------------------
 2 files changed, 95 deletions(-)

**Pull request merged**
